apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasten-server-opal-v3
  namespace: fasten
spec:
  selector:
    matchLabels:
      app: fasten-server-opal-v3
  replicas: 5
  template:
    metadata:
      labels:
        app: fasten-server-opal-v3
    spec:
      containers:
        - name: fasten-opal-v3
          image: docker.pkg.github.com/fasten-project/fasten/fasten.opal.v3:latest
          args: ["-k", "$(KAFKA_ADDR)", "-pl", "OPALV3", "-kt", "OPALV3=fasten.mvn.full"]
          ports:
            - containerPort: 3010
          env:
            - name: KAFKA_ADDR
              valueFrom:
                configMapKeyRef:
                  key: kafka.addr
                  name: kafka         
      nodeSelector:
        monster.node: "true"
      imagePullSecrets:
        - name: fasten.docker.registry