apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasten-server-db-monster
  namespace: fasten
spec:
  selector:
    matchLabels:
      app: fasten-server-db-monster
  replicas: 15
  template:
    metadata:
      labels:
        app: fasten-server-db-monster
    spec:
      containers:
        - name: fasten-server-db
          image: monster93/fasten.server.db:v0.1b
          args: ["-k", "kafka-0.kafka-headless.codefeedr:9092", "-kt", "MetadataDBExtension=fasten.OPAL.out", "-pl", "MetadataDBExtension", "-d", "$(PSQL_DB)", "-du", "$(PSQL_USER)"]
          ports:
            - containerPort: 3010
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: psql-pwd
                  name: psql.pwd
            - name: PSQL_DB
              valueFrom:
                secretKeyRef:
                  key: psql.db.url
                  name: psql.db
            - name: PSQL_USER
              valueFrom:
                secretKeyRef:
                  key: psql.db.username
                  name: psql.db.user       
      nodeSelector:
        monster.node: "true"
