name: Publish jar files

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
    branches:
    - master

env:
  IMAGE_NAME: fasten.server

jobs:
  push:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build jar
        run: mvn clean install
      - name: Rename jars
        run: mv docker/server/server-0.0.1-SNAPSHOT-with-dependencies.jar fasten-server.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: fasten-server.jar
          path: .
